doctrine:
     dbal:
         driver: "pdo_pgsql"
         server_version: "12.4"
         charset: utf8mb4
         default_table_options:
         charset: utf8mb4
         collate: utf8mb4_unicode_ci
         url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
